neo:
    hello: dev update1122

spring:
  application:
    name: eureka-consumer
server:
  port: 8001
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
